services:
  db:
    image: mysql:8.0
    container_name: healthcare_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: healthcare_api
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    command: gunicorn --bind 0.0.0.0:5000 app:app

volumes:
  mysql_data: